spring:
  application:
    name: activity-service

  datasource:
    url: jdbc:mysql://localhost:3306/activity_database
    username: root
    password: 202988
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
