spring:
  application:
    name: activity-service
  config:
    import:
      optional:configserver:http://config-server

spring.cloud:
  config:
    discovery:
      enabled: true
      service-id: config-server