spring:
  application:
    name: activity-service

  data:
    mongodb:
      uri: mongodb+srv://zarnholland:zarn1234@cluster0.dzkb3.mongodb.net/fitness-ms?retryWrites=true&w=majority&appName=Cluster0

#  datasource:
#    url: jdbc:mysql://localhost:3306/activity_database
#    username: root
#    password: 202988
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin123

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

rabbitmq:
  exchange:
    name: fitness.exchange
  queues:
    name: activity.queue
  routing:
    key: activity.tracking
