spring:
  application:
    name: api-gateway

  config:
    import: optional:configserver:http://config-server

spring.cloud:
  config:
    discovery:
      enabled: true
      service-id: config-server

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/