spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/fitness-ms

  config:
    import: optional:configserver:http://config-server

spring.cloud:
  config:
    discovery:
      enabled: true
      service-id: config-server


server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#OpenAPI
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui
    urls:
      - name: User Service
        url: /docs/userservice/v3/api-docs
      - name: Activity Service
        url: /docs/activityservice/v3/api-docs
      - name: Ai Service
        url: /docs/aiservice/v3/api-docs

#springdoc:
#  api-docs:
#    path: /v3/api-docs
#  swagger-ui:
#    path: /swagger-ui.html
#    urls[0]:
#      name: User Service
#      url: /docs/userservice/v3/api-docs
#    urls[1]:
#      name: Activity Service
#      url: /docs/activityservice/v3/api-docs
#    urls[2]:
#      name: Ai Service
#      url: /docs/aiservice/v3/api-docs

#  springdoc.swagger-ui.path=/swagger-ui.html
#  springdoc.api-docs.path=/v3/api-docs
#  springdoc.swagger-ui.urls[0].name=Inventory Service
#  springdoc.swagger-ui.urls[0].url=/docs/inventoryservice/v3/api-docs
#  springdoc.swagger-ui.urls[1].name=Booking Service
#  springdoc.swagger-ui.urls[1].url=/docs/bookingservice/v3/api-docs