spring:
  data:
    mongodb:
      uri: mongodb+srv://zarnholland:zarn1234@cluster0.dzkb3.mongodb.net/fitness-ms?retryWrites=true&w=majority&appName=Cluster0


#  datasource:
#    url: jdbc:mysql://localhost:3306/ai_database
#    username: root
#    password: 202988
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin123



server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

rabbitmq:
  exchange:
    name: fitness.exchange
  queues:
    name: activity.queue
  routing:
    key: activity.tracking

gemini:
  api:
    url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent
    key: AIzaSyAwmr0aNV-eE9ecsf3R-kooj_Q5-aRxY3E